(GH-443) Adds Windows Explorer item check box view
chocolatey/boxstarter pull request #447
Opened 2020-10-14 23:48 UTC by demdante

Even though Boxstarter has existing functionality to modify Windows
Explorer's settings, the existing functionality did not allow for user's to configure the "Use check boxes to select items" setting.  This commit adds that functionality to the existing set-windowsexploreroptions function.

Boxstarter will continue to work even if this change is not implemented, as this change is meant as an enhancement, not a bug fix.

## Description
I modified the Set-WindowsExplorerOptions.ps1 file in the following ways:
- Added two additional parameters that follow the same naming convention of all of the other parameters: "EnableItemCheckBoxes" and "DisableItemCheckBoxes"
- Added comment based help entries for each parameter describing their functionality
- Added two lines of code which would configure the check box settings for Windows Explorer

I also modified the WinConfig.cshtml file by modifying the two "Set-WindowsExplorerOptions" function examples to include each new parameter.

## Related Issue

Fixes #443 

## Motivation and Context

## How Has This Been Tested?

1. I spun up a fresh windows 10 vm
2. installed boxstarter
3. Replaced the contents of set-windowsexploreroptions in Boxstarter.Winconfig module with the modified script
4. wrote a one line boxstarter script using the command
5. Passed the script as an argument to install-boxstarterpackage

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/chocolatey/boxstarter/blob/master/CONTRIBUTING.md) document.
- [x] All new and existing tests passed.

2020-10-15 07:33 UTC, mwallner requested changes
Hey @demdante , thank you for implementing this!

the changes itself look great, just one nitpick: the feature you're referring to/implementing is originally called **"Use check boxes to select items"** (that's what's being displayed in Windows Explorer)
Could we at least update the comment based help and (maybe) as well find better-matching parameter names?
Maybe `-EnableItemSelectionCheckBoxes` ?

2020-10-15 08:13 UTC, pauby commented
@demdante Can you update the issue with the information requested. Until that is done we won't be in a position to merge this.

2020-10-15 18:04 UTC, demdante commented
@pauby The changes that @mwallner is suggesting are changes to the script, like improving the comment based help and choosing better parameters, not modifying the issue itself.  @mwallner I have no problem updating the help based comment section with the information concerning check boxes making selections (as the very nature of help based comments is to provide information), but I want to push back a little on modifying the parameter name.  Yes, you are correct.  If you go into Windows explorer, select the "view" tab, select "options", then select the "view" tab in the pop up window, then the full description of the feature is titled what you have said it is.  However, I made my changes based on the following criteria:
1. It matches the wording of the parameters that already exist in the function
2. Assuming that the part that you are referring to that you want added to the help based comment and included in the parameter name is "**to select items**".  I didn't include this part for two reasons: because I believe that it makes the parameters more confusing  and because it is not relevant to what the parameter actually does.  The naming of the parameters and the contents of help based comments only reference what the parameter does to windows explorer.  The act of "making selections" is an action performed by users, which the check boxes facilitate, but the parameter itself in the script does not make selections.  This is also why I believe it might confuse users, as they might think that the parameter is going to make some kind of selection in Windows Explorer.  Also, if we want to discuss how Windows Explorer words the feature, it actually does so in 2 places: the first being where @mwallner mentioned, the other being here:

![image](https://user-images.githubusercontent.com/64720591/96167769-634f4e80-0f0f-11eb-8e97-38e1287f128a.png)

The main options menu offers more context as to what the check boxes allow you to do, but that information is not relevant to what is actually being done to windows explorer.  So too, I think, should be how the parameter and help based content should be handled: The parameter name is given a name indicating **only** the actions were are performed against Windows Explorer, and any further context about what this feature enables users to **do after the fact** is explained in the help based comment.  Can we compromise on that?  Keep the parameter names and update the help based comment?

2020-10-15 19:01 UTC, mwallner commented
now THAT is an extensive answer :smile:

@demdante - I think @pauby was referring to the additional information he'd like to see in the Issue that's linked with this PR, not what I commented above.

> Can we compromise on that? Keep the parameter names and update the help based comment?

Sure, I'd be happy with that.

2020-10-15 21:29 UTC, demdante commented
Ok.  I made the changes to the files.  However, it embarrasses me to admit that I am not sure what to do now.  Do I delete this pull request and create another with the updated changes?  Is there a way for me to merge another commit into this pull request?  I am not sure.....

2020-10-15 22:04 UTC, gep13 commented
Yes, this is definitely possible. No need to close this PR and create a new one. Not in a position to do this just now, but I can write some notes here tomorrow on what you would need to do.

2020-10-16 06:41 UTC, gep13 commented
Hmm, having said what I said last night, I have just had a closer look, and looks like _something_ isn't quite right with this PR.

I am not sure how you got to this state, but the changes in the PR include some git related changes for merging files.  I am referring to the `<<<<<<< HEAD` in the changes.

Normally, I would be suggesting that you follow the steps in the contributing documentation here:

https://github.com/chocolatey/boxstarter/blob/master/CONTRIBUTING.md#respond-to-feedback-on-pull-request

But in this instance, it might be easier to make the changes again on a new branch, and submit a new PR, as I don't know the best way to resolve what I am seeing in the changes.

2020-10-28 02:48 UTC, demdante commented
@gep13 Yeah.  It got all screwed up, didn't it...  I will just create a new pull request on a different branch and close this one.

2020-10-28 21:01 UTC, closed without merging