Fix Boxstarter Package Parameter '-StopOnPackageFailure'
chocolatey/boxstarter pull request #452
Opened 2020-10-19 18:15 UTC by mwallner

## Description
In the code that evaluates Boxstarter Package Parameters, 'StopOnPackagaFailure' is only recognized (and therefore stripped from the 'chocolatey parameter string) if, and only if 'RebootCodes' were present in the original parameter string.

## Related Issue
Fixes #451

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/chocolatey/boxstarter/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-10-19 19:06 UTC, pauby requested changes

2020-10-19 19:06 UTC, pauby commented on tests/Chocolatey/Chocolatey.tests.ps1
> +
These tests don't specifically test for the issue this is fixing? There is no mention of `RebootCodes`?

2020-10-19 19:06 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> -            if (@("-RebootCodes", "--RebootCodes") -contains $a) {
Where does `--RebootCodes` come from?

2020-10-19 19:06 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> -            if (@("-StopOnPackageFailure", "--StopOnPackageFailure") -contains $a) {
Where does `--StopOnPackageFailure` come from?

2020-10-19 19:06 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +
You're removing the comments for this. If those comments are no longer valid can you add corrected comments?

2020-10-19 19:13 UTC, mwallner commented on tests/Chocolatey/Chocolatey.tests.ps1
> +
prior to this fix this test failed, now it passes

2020-10-19 19:14 UTC, mwallner commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +
nay, it's been moved to line 162ff

2020-10-19 19:15 UTC, mwallner commented on Boxstarter.Chocolatey/Chocolatey.ps1
> -            if (@("-RebootCodes", "--RebootCodes") -contains $a) {
arbitrary Boxstarter Chocolatey invocation - i.e. `choco <something> --RebootCodes @(1,2,3,4)`

2020-10-19 19:15 UTC, mwallner commented on Boxstarter.Chocolatey/Chocolatey.ps1
> -            if (@("-StopOnPackageFailure", "--StopOnPackageFailure") -contains $a) {
see comment above

2020-10-20 08:08 UTC, pauby commented on tests/Chocolatey/Chocolatey.tests.ps1
> +
We still don't appear to be testing for this _specific_ scenario?

2020-10-20 08:08 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> -            if (@("-RebootCodes", "--RebootCodes") -contains $a) {
But `--RebootCodes` is not a choco parameter?

2020-10-20 08:09 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> -            if (@("-StopOnPackageFailure", "--StopOnPackageFailure") -contains $a) {
But `--StopOnPackageFailure` is not a choco parameter?

2020-10-20 08:11 UTC, pauby commented on Boxstarter.Chocolatey/Chocolatey.ps1
> +
My bad. Reviewing PR's in here is hard. I'm switch to VS Code.

2020-10-20 08:12 UTC, mwallner commented on tests/Chocolatey/Chocolatey.tests.ps1
> +
well.. imo it is, since https://github.com/chocolatey/boxstarter/pull/452/files/878675eb082550c7183cc1ae7a2f2b9725b39852#diff-aeccdb912d0f033a98d9a83b37de5a528837cab1c653281a81fc03f382c21ec5R460 already tests for `RebootCodes` AND `StopOnPackageFailure` - to be fair, there is no test that specifically only checks for `RebootCodes` alone.
happy to add another testcase later today.

2020-10-20 08:17 UTC, pauby commented
Can you update your commit messages to reference the issue number - ie. `(GH-451) <COMMIT MESSAGE>`?

2021-01-19 12:20 UTC, pauby commented on tests/Chocolatey/Chocolatey.tests.ps1
> +
I've added #466 to cover this.

2021-01-19 12:36 UTC, pauby approved these changes

2021-01-19 12:38 UTC, merged

2021-01-19 12:45 UTC, pauby commented
@mwallner Awesome work! Thanks for your contribution!